#!/bin/bash

if [[ ( -z "$DPKG_MAINTSCRIPT_PACKAGE" ) || ( -z "$DPKG_ADMINDIR" ) ]]; then
    exit 1
fi
. $DPKG_ADMINDIR/info/$DPKG_MAINTSCRIPT_PACKAGE.get_icon_file

cat <<EOF >> $icon_file
[Desktop Entry]
Name=Conv2XviD
Exec=/usr/bin/conv2xvid
Icon=/etc/convertx/XviD.ico
Terminal=false
Type=Application
EOF

chown $SUDO_USER $icon_file

#DEBHELPER#
