#!/bin/bash

### TODO: move this into a common file ###
if [[ ( -z "$HOME" ) || ( -z "$DPKG_MAINTSCRIPT_PACKAGE" ) || ( -z "$DPKG_ADMINDIR" ) ]]; then
    exit 1
fi
desktop_path=$(fgrep XDG_DESKTOP_DIR $HOME/.config/user-dirs.dirs | sed 's#"##g')
desktop_name=$(basename $desktop_path)
icon_file="$HOME/$desktop_name/Conv2XviD.desktop"
###########################################

cat <<EOF >> $icon_file
[Desktop Entry]
Name=Conv2XviD
Exec=/usr/bin/conv2xvid
Icon=/etc/convert-x/XviD.ico
Terminal=false
Type=Application
EOF

chown $SUDO_USER $icon_file

#DEBHELPER#
